export enum Command {
    newGame = "new game",
    play = "play",
    about = "about",
    theme = "theme",
    dosTheme = "msdos",
    darkTheme = "dark",
    matrixTheme = "matrix",
    bloodTheme = "blood",
    partyStats = "party stats",
    enemyStats = "enemy stats",
    clear = "clear",
    help = "help",
    gameStats = "game stats",
    inventory = "inventory",
    use = "use",
}