export enum Command {
    newGame = "new game",
    play = "play",
    about = "about",
    dosTheme = "theme msdos",
    darkTheme = "theme dark",
    matrixTheme = "theme matrix",
    bloodTheme = "theme blood",
    partyStats = "party stats",
    enemyStats = "enemy stats",
    clear = "clear",
    help = "help",
    gameStats = "game stats",
    inventory = "inventory",
    use = "use",
}